language: android
android:
  components:
    - build-tools-15.0.0
    - android-15
    - android-L
    - sys-img-x86-android-tv-l
    - add-on
    - extra
script: ./gradlew assembleDebug

before_script:
 - chmod +x gradlew
